import React from 'react';
import { SummaryStats } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { CheckCircle2, AlertCircle, TrendingUp, DollarSign, Lightbulb, Sparkles, Download } from 'lucide-react';

interface DashboardProps {
  stats: SummaryStats;
}

export const Dashboard: React.FC<DashboardProps> = ({ stats }) => {
  const { analysis } = stats;

  const handleExportReport = () => {
    const reportContent = `
=== รายงานสรุปผลการตรวจสอบยอด (Manager's Summary) ===
วันที่: ${new Date().toLocaleDateString('th-TH')} เวลา: ${new Date().toLocaleTimeString('th-TH')}

1. ภาพรวม (Overview)
----------------------------------------
- รายการทั้งหมดจาก Bank: ${stats.totalBankRecords} รายการ
- รายการทั้งหมดจาก Book: ${stats.totalBookRecords} รายการ
- ความแม่นยำ (Match Rate): ${stats.matchPercentage.toFixed(2)}%
- จับคู่สำเร็จ: ${stats.matchedCount} รายการ
- ผลต่างสุทธิ (Net Diff): ${analysis.netDifference.toLocaleString()} บาท

2. รายการคงค้าง (Pending Items)
----------------------------------------
- ตกค้างใน Bank: ${stats.unmatchedBankCount} รายการ
- ตกค้างใน Book: ${stats.unmatchedBookCount} รายการ
- AI Smart Fixes: ${stats.smartFixCount} รายการ

3. สิ่งที่ AI เรียนรู้ (AI Key Observations)
----------------------------------------
${analysis.aiObservation.map((obs) => `- ${obs}`).join('\n')}

4. สาเหตุหลัก (Root Cause Analysis)
----------------------------------------
${analysis.primaryCause}

5. คำแนะนำเพื่อปรับปรุง (Action Plan)
----------------------------------------
${analysis.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

----------------------------------------
Generated by AutoReconcile Pro
`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `reconcile_report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6 mb-8">
      
      {/* Row 1: KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-5">
        <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-slate-400 text-sm font-bold uppercase tracking-wider">ความแม่นยำ</h3>
            <div className="p-2.5 bg-emerald-100 rounded-2xl">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
            </div>
          </div>
          <div className="text-3xl font-extrabold text-slate-700">{stats.matchPercentage.toFixed(1)}%</div>
          <div className="text-xs font-medium text-slate-400 mt-1">จาก {stats.totalBankRecords} รายการ</div>
        </div>

        <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-slate-400 text-sm font-bold uppercase tracking-wider">AI Fixes</h3>
            <div className="p-2.5 bg-violet-100 rounded-2xl">
              <Lightbulb className="w-5 h-5 text-violet-500" />
            </div>
          </div>
          <div className="text-3xl font-extrabold text-violet-500">{stats.smartFixCount}</div>
          <div className="text-xs font-medium text-slate-400 mt-1">รายการที่ AI ช่วยแก้ไข</div>
        </div>

        <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-slate-400 text-sm font-bold uppercase tracking-wider">รายการคงค้าง</h3>
            <div className="p-2.5 bg-amber-100 rounded-2xl">
              <AlertCircle className="w-5 h-5 text-amber-500" />
            </div>
          </div>
          <div className="text-3xl font-extrabold text-slate-700">
            {stats.unmatchedBankCount + stats.unmatchedBookCount}
          </div>
          <div className="text-xs font-medium text-slate-400 mt-1 flex space-x-2">
            <span className="text-rose-400">Bank: {stats.unmatchedBankCount}</span>
            <span>|</span>
            <span className="text-amber-400">Book: {stats.unmatchedBookCount}</span>
          </div>
        </div>

        <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-slate-400 text-sm font-bold uppercase tracking-wider">ผลต่างสุทธิ</h3>
            <div className={`p-2.5 rounded-2xl ${analysis.netDifference === 0 ? 'bg-slate-100' : 'bg-rose-100'}`}>
              <DollarSign className={`w-5 h-5 ${analysis.netDifference === 0 ? 'text-slate-500' : 'text-rose-500'}`} />
            </div>
          </div>
          <div className={`text-3xl font-extrabold ${analysis.netDifference === 0 ? 'text-slate-700' : 'text-rose-500'}`}>
            {Math.abs(analysis.netDifference).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
          <div className="text-xs font-medium text-slate-400 mt-1">
            {analysis.netDifference > 0 ? 'เงินเกิน (Bank > Book)' : analysis.netDifference < 0 ? 'เงินขาด (Book > Bank)' : 'ยอดตรงกัน (Balanced)'}
          </div>
        </div>
      </div>

      {/* Row 2: Analysis & Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left: AI Insights Panel */}
        <div className="lg:col-span-1 bg-gradient-to-br from-violet-300 via-purple-300 to-fuchsia-300 rounded-3xl shadow-xl shadow-purple-200 p-7 text-white flex flex-col justify-between relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-20 transform rotate-12">
            <Sparkles className="w-40 h-40 text-white" />
          </div>
          
          <div className="relative z-10">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center space-x-2 bg-white/20 px-3 py-1.5 rounded-full backdrop-blur-sm">
                 <Sparkles className="w-4 h-4 text-yellow-200" />
                 <h3 className="text-sm font-bold tracking-wide text-white">AI Summary</h3>
              </div>
              <button 
                onClick={handleExportReport}
                className="bg-white text-violet-500 hover:bg-white/90 text-xs font-bold px-3 py-2 rounded-xl flex items-center transition-all shadow-sm"
              >
                <Download className="w-3 h-3 mr-1" />
                Export
              </button>
            </div>
            
            <div className="mb-8">
              <p className="text-violet-900/60 text-[10px] uppercase font-bold mb-3 tracking-widest">Key Observations</p>
              <ul className="space-y-3">
                {analysis.aiObservation.map((obs, idx) => (
                  <li key={idx} className="text-sm font-medium text-white flex items-start leading-relaxed">
                    <span className="bg-white/30 rounded-full w-1.5 h-1.5 mt-2 mr-3 flex-shrink-0"></span>
                    {obs}
                  </li>
                ))}
              </ul>
            </div>

            <div className="mb-0 border-t border-white/20 pt-5">
              <p className="text-violet-900/60 text-[10px] uppercase font-bold mb-1 tracking-widest">Primary Cause</p>
              <p className="text-xl font-bold text-white tracking-tight">{analysis.primaryCause}</p>
            </div>
          </div>

          <div className="relative z-10 bg-white/90 rounded-2xl p-5 backdrop-blur-md mt-6 shadow-lg shadow-purple-900/10">
            <h4 className="text-xs font-extrabold text-violet-500 mb-3 flex items-center uppercase tracking-wide">
              <TrendingUp className="w-4 h-4 mr-2" />
              Recommended Actions
            </h4>
            <ul className="space-y-2">
              {analysis.recommendations.length > 0 ? analysis.recommendations.map((rec, idx) => (
                <li key={idx} className="text-xs font-medium text-slate-600 flex items-start">
                  <span className="mr-2 text-violet-400 font-bold">{idx + 1}.</span>
                  {rec}
                </li>
              )) : (
                <li className="text-xs font-medium text-slate-600 flex items-start">
                  <span className="mr-2 text-emerald-400">✓</span>
                  ระบบทำงานได้ดี ไม่พบข้อผิดพลาดร้ายแรง
                </li>
              )}
            </ul>
          </div>
        </div>

        {/* Right: Charts */}
        <div className="lg:col-span-2 bg-white p-8 rounded-3xl shadow-sm border border-slate-100">
          <h3 className="text-lg font-bold text-slate-700 mb-8 flex items-center">
            <div className="p-2 bg-rose-100 rounded-xl mr-3">
               <AlertCircle className="w-5 h-5 text-rose-500" />
            </div>
            วิเคราะห์สาเหตุข้อผิดพลาด
          </h3>
          <div className="h-72 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={analysis.errorDistribution}
                layout="vertical"
                margin={{ top: 5, right: 30, left: 40, bottom: 5 }}
              >
                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f1f5f9" />
                <XAxis type="number" hide />
                <YAxis 
                  dataKey="name" 
                  type="category" 
                  width={140} 
                  tick={{fontSize: 12, fill: '#64748b', fontWeight: 600}}
                  axisLine={false}
                  tickLine={false}
                />
                <Tooltip 
                  cursor={{fill: '#f8fafc'}}
                  contentStyle={{
                    borderRadius: '16px', 
                    border: 'none', 
                    boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)', 
                    backgroundColor: 'rgba(255, 255, 255, 0.95)',
                    padding: '12px'
                  }}
                  itemStyle={{color: '#475569', fontWeight: 600, fontSize: '13px'}}
                />
                <Bar dataKey="value" radius={[0, 8, 8, 0]} barSize={24}>
                  {analysis.errorDistribution.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
};